import {test} from 'uvu'
import './create-app.js'
import './skip-update.js'
import './stringify.js'
import './stringify-with-keys.js'
import './dom-view/add-attributes.js'
import './dom-view/add-children.js'
import './dom-view/add-children-with-keys.js'
import './dom-view/add-event.js'
import './dom-view/add-text.js'
import './dom-view/after-update.js'
import './dom-view/change-event.js'
import './dom-view/no-changes-dynamic.js'
import './dom-view/no-changes-static.js'
import './dom-view/node-to-node.js'
import './dom-view/node-to-text.js'
import './dom-view/remove-attributes.js'
import './dom-view/remove-children.js'
import './dom-view/remove-children-with-keys.js'
import './dom-view/remove-event.js'
import './dom-view/remove-text.js'
import './dom-view/root-after-update.js'
import './dom-view/svg.js'
import './dom-view/text-to-node.js'
import './dom-view/text-to-text.js'
import './html/attributes.js'
import './html/children.js'
import './html/closing-elements.js'
import './html/text.js'
import './html/throws-bad-roots.js'
import './html/throws-quotes.js'

test.run()
